spring:
  datasource:
    dynamic:
      primary: pz
      static: false
      datasource:
        pz:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: oracle.jdbc.driver.OracleDriver # mysql的驱动你可以配置别的关系型数据库
          url: jdbc:oracle:thin:@(description=(address_list=(address=(host=10.119.1.248)(protocol=tcp)(port=1522))(address=(host=10.119.1.250)(protocol=tcp)(port=1522))(load_balance=yes)(failover=yes))(connect_data=(service_name=jwzh))) # 数据源地址
          username: pz2010 # 用户名
          password: pz2010123456 # 密码
        nbdh:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: oracle.jdbc.driver.OracleDriver # mysql的驱动你可以配置别的关系型数据库
          url: jdbc:oracle:thin:@41.204.5.126:1521:orcl # 数据源地址
          username: zzrk2020 # 用户名
          password: 123456 # 密码
  #    filters: stat,wall,log4j,config
  #    max-active: 100
  #    initial-size: 1
  #    max-wait: 60000
  #    min-idle: 1
  #    time-between-eviction-runs-millis: 60000
  #    min-evictable-idle-time-millis: 300000
  #    validation-query: select 'x' from dual
  #    test-while-idle: true
  #    test-on-borrow: false
  #    test-on-return: false
  #    pool-prepared-statements: true
  #    max-open-prepared-statements: 50
  #    max-pool-prepared-statement-per-connection-size: 20
  data:
    mongodb:
      database: zaxq
      host: 41.204.5.126
      port: 27017
      password: 123456zaxq
      username: pzzaxq
  jpa:
    database: oracle
  # redis
  redis:
    database: 0
    host:  41.204.5.126
    port: 6379
#    password: 123456zaxq
server:
  port: 8501
#数据卷目录
dataDir: 'Z:\\data\\mongo\\db\\data'